### ISSUE TITLE
Game crashes after totem placement

### ISSUE THREAD

**Issue by alobaids** [MusicAdam/TotemDefender#54]
The game will crash when player 1 tries to aim the canon. Both going up or down cause the game to crash. This is the exception that fires:
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.totemdefender.entities.WeaponEntity.rotateDown(WeaponEntity.java:204)
    at com.totemdefender.states.BattleState.update(BattleState.java:172)
    at com.totemdefender.states.StateManager.update(StateManager.java:50)
    at com.totemdefender.TotemDefender.render(TotemDefender.java:236)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:208)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

**Comment by MusicAdam** [comment]
try pulling again and refreshing

**Comment by MusicAdam** [comment]
looks like its only happening for the catapult

**Comment by alobaids** [comment]
no it only happens with the cannon. However, if the cannon overlaps the catapult, which is also a bug, the game works normaly.

**Comment by alobaids** [comment]
I think I pinpointed specifically what happens. If the cannon is being used, the game will crash once player 1 tries to aim with his or her weapon. If the cannon is overlapping, than the game works.

**Comment by MusicAdam** [comment]
what do you mean if the cannon is overlapping?
